# Generated by Django 4.2.14 on 2024-10-20 18:53

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_user_options_product_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigIntegerField(default=ecommerce.models.generate_category_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigIntegerField(default=ecommerce.models.generate_product_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.BigIntegerField(default=ecommerce.models.generate_promotion_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigIntegerField(default=ecommerce.models.generate_review_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigIntegerField(default=ecommerce.models.generate_wishlist_id, primary_key=True, serialize=False),
        ),
    ]
